{% set version = "0.4.1" %}
{% set name = "cluster_tools" %}

package:
  name: cluster_tools
  version: {{ version }}

source:
  url: https://github.com/constantinpape/cluster_tools/archive/{{ version }}.tar.gz
  sha256: 85bd637e9fa66db14bdd5dacbaf37e6f9c80b6cc43c9e89d4b8d7f99babc1cfb

build:
  number: 0
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-elf
    - pybdv
    - luigi

test:
  imports:
    - cluster_tools
    - cluster_tools.workflows

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Distributed segmentation for bio-image-analysis.
  home: https://github.com/constantinpape/cluster_tools

extra:
  recipe-maintainers:
    - constantinpape
