{% set version = "0.4.8" %}
{% set name = "cluster_tools" %}

package:
  name: cluster_tools
  version: {{ version }}

source:
  url: https://github.com/constantinpape/cluster_tools/archive/{{ version }}.tar.gz
  sha256: 163fae730ad06bf49084f4a056d96f4d929d1f24d52644ea172cfb0918deeeaa

build:
  number: 1
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - python-elf
    - pybdv
    - luigi

test:
  requires:
    - python {{ python_min }}
  imports:
    - cluster_tools
    - cluster_tools.workflows

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Distributed segmentation for bio-image-analysis.
  home: https://github.com/constantinpape/cluster_tools

extra:
  recipe-maintainers:
    - constantinpape
