{% set version = "0.5.0" %}
{% set name = "cluster_tools" %}

package:
  name: cluster_tools
  version: {{ version }}

source:
  url: https://github.com/constantinpape/cluster_tools/archive/{{ version }}.tar.gz
  sha256: 1a5f7a8d17ef4bbb1c2c19e9c54c1003f95468918f4be51980ce1c4cbc6a35af

build:
  number: 0
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-elf
    - pybdv
    - luigi
    - affogato >=0.4.2
    - nifty >=1.2.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - cluster_tools
    - cluster_tools.workflows

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Distributed segmentation for bio-image-analysis.
  home: https://github.com/constantinpape/cluster_tools

extra:
  recipe-maintainers:
    - constantinpape
