{% set version = "0.4.7" %}
{% set name = "cluster_tools" %}

package:
  name: cluster_tools
  version: {{ version }}

source:
  url: https://github.com/constantinpape/cluster_tools/archive/{{ version }}.tar.gz
  sha256: 5fa7a309254d29dc972d6f21eb65135cbb00f9e3116894210abd08a34f209200

build:
  number: 0
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-elf
    - pybdv
    - luigi

test:
  imports:
    - cluster_tools
    - cluster_tools.workflows

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Distributed segmentation for bio-image-analysis.
  home: https://github.com/constantinpape/cluster_tools

extra:
  recipe-maintainers:
    - constantinpape
