{% set version = "0.5.1" %}
{% set name = "cluster_tools" %}

package:
  name: cluster_tools
  version: {{ version }}

source:
  url: https://github.com/constantinpape/cluster_tools/archive/{{ version }}.tar.gz
  sha256: 7b531ea24dc232d9564abd4a306a4bed069ce6e8392c5dc62e2a533b5becdafe

build:
  number: 0
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-elf
    - pybdv
    - luigi
    - affogato >=0.4.2
    - nifty >=1.2.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - cluster_tools
    - cluster_tools.workflows

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Distributed segmentation for bio-image-analysis.
  home: https://github.com/constantinpape/cluster_tools

extra:
  recipe-maintainers:
    - constantinpape
